<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iso_parsing_model" nsURI="iso_parsing_model" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="ISO26266">
    <eStructuralFeatures xsi:type="ecore:EReference" name="documents" upperBound="-1"
        eType="#//ISODocument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clauses" upperBound="-1"
        eType="#//Clause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refs" upperBound="-1" eType="#//Ref"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Paragraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderP" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainTextP" eSuperTypes="#//Paragraph"/>
  <eClassifiers xsi:type="ecore:EClass" name="SummationElP" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Summation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedP" eSuperTypes="#//Paragraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ref" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="used_at_offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="used_at_length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalRef" eSuperTypes="#//Ref">
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Clause"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalRef" eSuperTypes="#//Ref">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISODocument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherPs" upperBound="-1"
        eType="#//Paragraph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//RequirementSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in_document" eType="#//ISODocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" lowerBound="1"
        eType="#//HeaderP" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//Paragraph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="summations" upperBound="-1"
        eType="#//Summation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" eType="ecore:EClass ../iso_research_metamodel.ecore#//IsoRequirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Summation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="#//Paragraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//SummationElP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextSource" eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linenumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
